language: elixir
elixir: 1.4.2
otp_release:
  - 19.1
sudo: false
before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
before_script:
  - mix deps.get --only test
script:
  - mix test
